
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Computer
 */
public class FormYoneticiAnaEkran extends javax.swing.JFrame {

    DefaultTableModel model;
    Poliklinikler p=new Poliklinikler();
    
    DefaultTableModel modelDoktor;
    Doktor d=new Doktor();

    FormYoneticiAnaEkran(FormKullaniciGirisi aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form FormYoneticiAnaEkran
     */
    
    public void AdAktarma(String doktorAdi){
        lblYoneticiAdi.setText(doktorAdi);
    }
    
    public FormYoneticiAnaEkran() {
        initComponents();
        
        model=(DefaultTableModel) tabloPoliklinik.getModel();
        poliklinikGoruntule();
        
        modelDoktor=(DefaultTableModel) tabloDoktor.getModel();
        doktorGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        lblYoneticiAdi = new javax.swing.JLabel();
        btnGeriDon = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabloDoktor = new javax.swing.JTable();
        txtDoktor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTcAra = new javax.swing.JButton();
        btnTcSil = new javax.swing.JButton();
        btnDoktorEkle = new javax.swing.JButton();
        btnDoktorGuncelle = new javax.swing.JButton();
        btnDoktorListele = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtKullaniciAdi = new javax.swing.JTextField();
        txtSifre = new javax.swing.JTextField();
        txtTcNo = new javax.swing.JTextField();
        txtAd = new javax.swing.JTextField();
        txtSoyad = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtAdres = new javax.swing.JTextField();
        panel3 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabloPoliklinik = new javax.swing.JTable();
        txtIdAra = new javax.swing.JTextField();
        btnAra = new javax.swing.JButton();
        btnEkle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        txtAdEkle = new javax.swing.JTextField();
        txtIdSil = new javax.swing.JTextField();
        txtAdGuncelle = new javax.swing.JTextField();
        btnPoliklinikListele = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yönetici Ana Ekran");

        panel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel2.setText("Hoşgeldin Yönetici :");

        lblYoneticiAdi.setText("Yönetici Adı");

        btnGeriDon.setText("Kullnıcı Girişi'ne Geri Dön");
        btnGeriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYoneticiAdi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGeriDon)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblYoneticiAdi)
                    .addComponent(btnGeriDon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel2.setBackground(java.awt.SystemColor.activeCaption);

        tabloDoktor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sıra No", "Kullanıcı Adı", "Şifre", "Tc No", "Adı ", "Soyadı", "Tel No", "Adres"
            }
        ));
        tabloDoktor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloDoktorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabloDoktor);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Doktor İşlemleri");

        btnTcAra.setText("Tc No ya Göre Ara");
        btnTcAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTcAraActionPerformed(evt);
            }
        });

        btnTcSil.setText("Tc No'ya Göre Sil");
        btnTcSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTcSilActionPerformed(evt);
            }
        });

        btnDoktorEkle.setText("Ekle");
        btnDoktorEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoktorEkleActionPerformed(evt);
            }
        });

        btnDoktorGuncelle.setText("Güncelle");
        btnDoktorGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoktorGuncelleActionPerformed(evt);
            }
        });

        btnDoktorListele.setText("Listele");
        btnDoktorListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoktorListeleActionPerformed(evt);
            }
        });

        jLabel4.setText("Kullanıcı Adı :");

        jLabel5.setText("Şifre :");

        jLabel6.setText("Tc No :");

        jLabel7.setText("Ad :");

        jLabel8.setText("Soyad :");

        jLabel9.setText("Tel No :");

        jLabel10.setText("Adres :");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(19, 19, 19)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAdres)
                                    .addComponent(txtTel)
                                    .addComponent(txtSoyad)
                                    .addComponent(txtAd)
                                    .addComponent(txtTcNo)
                                    .addComponent(txtSifre)
                                    .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(btnDoktorEkle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDoktorListele, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnTcAra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(btnTcSil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDoktor, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnDoktorGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTcAra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTcNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTcSil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDoktorGuncelle))
                        .addGap(6, 6, 6)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDoktorListele)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(txtDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoktorEkle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel3.setBackground(java.awt.SystemColor.activeCaption);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Poliklinik İşlemleri");

        tabloPoliklinik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sıra No", "Poliklinik Adı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabloPoliklinik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloPoliklinikMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabloPoliklinik);
        if (tabloPoliklinik.getColumnModel().getColumnCount() > 0) {
            tabloPoliklinik.getColumnModel().getColumn(0).setResizable(false);
            tabloPoliklinik.getColumnModel().getColumn(1).setResizable(false);
        }

        btnAra.setText("Ara");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnGuncelle.setText("Güncelle");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        btnPoliklinikListele.setText("Listele");
        btnPoliklinikListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliklinikListeleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdAra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAdEkle)
                            .addComponent(txtIdSil)
                            .addComponent(txtAdGuncelle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuncelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPoliklinikListele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEkle)
                    .addComponent(txtAdEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSil)
                    .addComponent(txtIdSil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuncelle)
                    .addComponent(txtAdGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPoliklinikListele)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        
        p.setAd(txtAdEkle.getText());
        p.ekle();
        poliklinikGoruntule();
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
        p.setId(Integer.valueOf(txtIdAra.getText()));
        p.ara();
        model.setRowCount(0);
        
        ArrayList<Poliklinikler> kayitlar=new ArrayList<Poliklinikler>();
        kayitlar=p.ara();
        if(kayitlar!=null){
            for(Poliklinikler poliklinik: kayitlar)
            {
                Object [] eklenecek={poliklinik.getId(),poliklinik.getAd()};
                model.addRow(eklenecek);
            }
        }
    }//GEN-LAST:event_btnAraActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        p.setId(Integer.valueOf(txtIdSil.getText()));
        p.sil();
        poliklinikGoruntule();
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed

        int selectedRow=tabloPoliklinik.getSelectedRow();
        if(selectedRow==-1){
            if(model.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Poliklinik tablosu şu an boş.");
            }
            else{
                JOptionPane.showMessageDialog(this, "Lütfen güncellenecek bir poliklinik seçin");
            }
        }
        else{
            String ad=txtAdGuncelle.getText();
            int id=(int) model.getValueAt(selectedRow, 0);
            p.setId(id);
            p.setAd(ad);
            p.guncelle();
            poliklinikGoruntule();
        }
    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void tabloPoliklinikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloPoliklinikMouseClicked
        int selectedRow=tabloPoliklinik.getSelectedRow();
        txtAdGuncelle.setText(model.getValueAt(selectedRow,1).toString());
    }//GEN-LAST:event_tabloPoliklinikMouseClicked

    private void btnTcAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTcAraActionPerformed
        d.setTcNo(txtDoktor.getText());
        d.ara();
        modelDoktor.setRowCount(0);
        
        ArrayList<Doktor> kayitlar=new ArrayList<Doktor>();
        kayitlar=d.ara();
        if(kayitlar!=null){
            for(Doktor doktor: kayitlar)
            {
                Object [] eklenecek={doktor.getId(),doktor.getKullaniciAdi(),doktor.getSifre(),doktor.getTcNo(),doktor.getAd(),doktor.getSoyad(),doktor.getTel(),doktor.getAdres()};
                modelDoktor.addRow(eklenecek);
            }
        }
    }//GEN-LAST:event_btnTcAraActionPerformed

    private void btnTcSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTcSilActionPerformed
        
        d.setTcNo(txtDoktor.getText());
        d.sil();
        doktorGoruntule();
    }//GEN-LAST:event_btnTcSilActionPerformed

    private void btnPoliklinikListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliklinikListeleActionPerformed
        
        poliklinikGoruntule();
    }//GEN-LAST:event_btnPoliklinikListeleActionPerformed

    private void btnDoktorListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoktorListeleActionPerformed
        doktorGoruntule();
    }//GEN-LAST:event_btnDoktorListeleActionPerformed

    private void btnDoktorEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoktorEkleActionPerformed
        
        d.setKullaniciAdi(txtKullaniciAdi.getText());
        d.setSifre(txtSifre.getText());
        d.setTcNo(txtTcNo.getText());
        d.setAd(txtAd.getText());
        d.setSoyad(txtSoyad.getText());
        d.setTel(txtTel.getText());
        d.setAdres(txtAdres.getText());
        d.ekle();

        doktorGoruntule();
    }//GEN-LAST:event_btnDoktorEkleActionPerformed

    private void tabloDoktorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloDoktorMouseClicked
        
        int selectedRow=tabloDoktor.getSelectedRow();
        txtKullaniciAdi.setText(modelDoktor.getValueAt(selectedRow,1).toString());
        txtSifre.setText(modelDoktor.getValueAt(selectedRow,2).toString());
        txtTcNo.setText(modelDoktor.getValueAt(selectedRow,3).toString());
        txtAd.setText(modelDoktor.getValueAt(selectedRow,4).toString());
        txtSoyad.setText(modelDoktor.getValueAt(selectedRow,5).toString());
        txtTel.setText(modelDoktor.getValueAt(selectedRow,6).toString());
        txtAdres.setText(modelDoktor.getValueAt(selectedRow,7).toString());
    }//GEN-LAST:event_tabloDoktorMouseClicked

    private void btnDoktorGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoktorGuncelleActionPerformed
        int selectedRow=tabloDoktor.getSelectedRow();
        if(selectedRow==-1){
            if(model.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Doktor tablosu şu an boş.");
            }
            else{
                JOptionPane.showMessageDialog(this, "Lütfen güncellenecek bir doktor seçin");
            }
        }
        else{
            int id=(int) modelDoktor.getValueAt(selectedRow, 0);
            String k_ad=txtKullaniciAdi.getText();
            String sifre=txtSifre.getText();
            String tcNo=txtTcNo.getText();
            String ad=txtAd.getText();
            String soyad=txtSoyad.getText();
            String tel=txtTel.getText();
            String adres=txtAdres.getText();
            
            d.setId(id);
            d.setKullaniciAdi(k_ad);
            d.setSifre(sifre);
            d.setTcNo(tcNo);
            d.setAd(ad);
            d.setSoyad(soyad);
            d.setTel(tel);
            d.setAdres(adres);
            
            d.guncelle();
            doktorGoruntule();
        }
    }//GEN-LAST:event_btnDoktorGuncelleActionPerformed

    private void btnGeriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriDonActionPerformed
        
        setVisible(false);
        FormKullaniciGirisi ac=new FormKullaniciGirisi();
        ac.setVisible(true);
    }//GEN-LAST:event_btnGeriDonActionPerformed

    public void doktorGoruntule(){
        modelDoktor.setRowCount(0);
        
        ArrayList<Doktor> kayitlar=new ArrayList<Doktor>();
        kayitlar=d.listele();
        if(kayitlar!=null){
            for(Doktor doktor: kayitlar)
            {
                Object [] eklenecek={doktor.getId(),doktor.getKullaniciAdi(),doktor.getSifre(),doktor.getTcNo(),doktor.getAd(),doktor.getSoyad(),doktor.getTel(),doktor.getAdres()};
                modelDoktor.addRow(eklenecek);
            }
        }
    }
    
    public void poliklinikGoruntule(){
        model.setRowCount(0);
        
        ArrayList<Poliklinikler> kayitlar=new ArrayList<Poliklinikler>();
        kayitlar=p.listele();
        if(kayitlar!=null){
            for(Poliklinikler poliklinik: kayitlar)
            {
                Object [] eklenecek={poliklinik.getId(),poliklinik.getAd()};
                model.addRow(eklenecek);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormYoneticiAnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormYoneticiAnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormYoneticiAnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormYoneticiAnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormYoneticiAnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnDoktorEkle;
    private javax.swing.JButton btnDoktorGuncelle;
    private javax.swing.JButton btnDoktorListele;
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGeriDon;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnPoliklinikListele;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton btnTcAra;
    private javax.swing.JButton btnTcSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblYoneticiAdi;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JTable tabloDoktor;
    private javax.swing.JTable tabloPoliklinik;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtAdEkle;
    private javax.swing.JTextField txtAdGuncelle;
    private javax.swing.JTextField txtAdres;
    private javax.swing.JTextField txtDoktor;
    private javax.swing.JTextField txtIdAra;
    private javax.swing.JTextField txtIdSil;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JTextField txtSifre;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTcNo;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
