
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Computer
 */
public class FormKullaniciGirisi extends javax.swing.JFrame {
    Yonetici y=new Yonetici();
    Doktor d=new Doktor();
    Hasta h=new Hasta();
    
    /**
     * Creates new form FormKullaniciGirisi
     */
    public FormKullaniciGirisi() {
        initComponents();
        String underline1="<html><u>"+ lblYeniHasta.getText()+"</u></html>";
        lblYeniHasta.setText(underline1);
        
        String underline2="<html><u>"+ lblYeniDoktor.getText()+"</u></html>";
        lblYeniDoktor.setText(underline2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKullaniciAdi = new javax.swing.JTextField();
        lblYeniHasta = new javax.swing.JLabel();
        lblYeniDoktor = new javax.swing.JLabel();
        btnHasta = new javax.swing.JButton();
        btnDoktor = new javax.swing.JButton();
        btnYonetici = new javax.swing.JButton();
        txtSifre = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kullanıcı Girişi");
        setBounds(new java.awt.Rectangle(500, 250, 0, 0));

        panel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setText("Kullanıcı Adı :");

        jLabel2.setText("Şifre :");

        lblYeniHasta.setText("Yeni Hasta Kayıt");
        lblYeniHasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYeniHastaMouseClicked(evt);
            }
        });

        lblYeniDoktor.setText("Yeni Doktor Kayıt");
        lblYeniDoktor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYeniDoktorMouseClicked(evt);
            }
        });

        btnHasta.setText("Hasta Girişi Yap");
        btnHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHastaActionPerformed(evt);
            }
        });

        btnDoktor.setText("Doktor Girişi Yap");
        btnDoktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoktorActionPerformed(evt);
            }
        });

        btnYonetici.setText("Yönetici Girişi Yap");
        btnYonetici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYoneticiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblYeniHasta)
                    .addComponent(lblYeniDoktor))
                .addGap(45, 45, 45)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnYonetici, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(txtKullaniciAdi)
                    .addComponent(btnHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoktor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSifre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYeniHasta)
                    .addComponent(btnHasta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYeniDoktor)
                    .addComponent(btnDoktor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnYonetici)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblYeniHastaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYeniHastaMouseClicked
        FormHastaKayit ac=new FormHastaKayit();
        ac.setVisible(true);
    }//GEN-LAST:event_lblYeniHastaMouseClicked

    private void lblYeniDoktorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYeniDoktorMouseClicked
        FormDoktorKayit ac=new FormDoktorKayit();
        ac.setVisible(true);
    }//GEN-LAST:event_lblYeniDoktorMouseClicked

    private void btnYoneticiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYoneticiActionPerformed

        String kullaniciAdi=txtKullaniciAdi.getText();
        String parola=String.valueOf(txtSifre.getPassword());
        
        FormYoneticiAnaEkran yoneticiEkrani=new FormYoneticiAnaEkran();
        
        boolean girisBasarili=y.girisYap(kullaniciAdi, parola);
        if(girisBasarili){
            setVisible(false);

            yoneticiEkrani.setVisible(true);
            yoneticiEkrani.AdAktarma(y.getAd()+" "+y.getSoyad());
        }        
        else JOptionPane.showMessageDialog(this, "Hatalı Giriş.");
    }//GEN-LAST:event_btnYoneticiActionPerformed

    private void btnDoktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoktorActionPerformed

        FormDoktorAnaEkran doktorEkrani=new FormDoktorAnaEkran();
        
        String kullaniciAdi=txtKullaniciAdi.getText();
        String parola=String.valueOf(txtSifre.getPassword());
        
        boolean girisBasarili=d.girisYap(kullaniciAdi, parola);
        if(girisBasarili){
            
            setVisible(false);
            
            doktorEkrani.doktorVerileriGetir(d.getId(),d.getKullaniciAdi(),d.getSifre(),d.getTcNo(),d.getAd(),d.getSoyad(),d.getTel(),d.getAdres());
            doktorEkrani.AdAktarma(d.getAd()+" "+d.getSoyad());
            doktorEkrani.doktorAdGetir(d.getAd()+" "+d.getSoyad());
            doktorEkrani.doktorRandevuAra(d.getId());
            doktorEkrani.doktorReceteAra(d.getId());
            doktorEkrani.setVisible(true);
            
            //System.exit(0);
        }
        else JOptionPane.showMessageDialog(this, "Hatalı Giriş.");
    }//GEN-LAST:event_btnDoktorActionPerformed

    private void btnHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHastaActionPerformed
        
        FormHastaAnaEkran hastaEkrani=new FormHastaAnaEkran();
        String kullaniciAdi=txtKullaniciAdi.getText();
        String parola=String.valueOf(txtSifre.getPassword());
        
        boolean girisBasarili=h.girisYap(kullaniciAdi, parola);
        
        if(girisBasarili){
            setVisible(false);
            
            hastaEkrani.hastaVerileriGetir(h.getId(),h.getKullaniciAdi(),h.getSifre(),h.getTcNo(),h.getAd(),h.getSoyad(),h.getTel(),h.getAdres());
            hastaEkrani.AdAktarma(h.getAd()+" "+h.getSoyad());
            hastaEkrani.HastaGetir(h.getAd()+ " "+h.getSoyad());
            hastaEkrani.hastaRandevuAra(h.getId());
            hastaEkrani.hastaReceteAra(h.getId());
            hastaEkrani.setVisible(true);
            
        }
        else JOptionPane.showMessageDialog(this, "Hatalı Giriş.");
    }//GEN-LAST:event_btnHastaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKullaniciGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKullaniciGirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoktor;
    private javax.swing.JButton btnHasta;
    private javax.swing.JButton btnYonetici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblYeniDoktor;
    private javax.swing.JLabel lblYeniHasta;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
